services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  backend:
    build:
      context: .
      dockerfile: ./packages/backend/Dockerfile
    depends_on:
      - mongo
    environment:
      PORT: 3000
      MONGODB_URL: mongodb://root:example@mongo:27017/
    ports:
      - 3000:3000

  web:
    build:
      context: .
      dockerfile: ./packages/web/Dockerfile
    ports:
      - 80:80
