/* tslint:disable */
/* eslint-disable */
/**
 * @betamanga/backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0-placeholder
 * Contact: kilian.panot@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Components
 */
export interface Components {
    /**
     * 
     * @type {object}
     * @memberof Components
     */
    schemas?: object;
    /**
     * 
     * @type {object}
     * @memberof Components
     */
    responses?: object;
    /**
     * 
     * @type {object}
     * @memberof Components
     */
    parameters?: object;
    /**
     * 
     * @type {object}
     * @memberof Components
     */
    examples?: object;
    /**
     * 
     * @type {object}
     * @memberof Components
     */
    requestBodies?: object;
    /**
     * 
     * @type {object}
     * @memberof Components
     */
    headers?: object;
    /**
     * 
     * @type {object}
     * @memberof Components
     */
    securitySchemes?: object;
    /**
     * 
     * @type {object}
     * @memberof Components
     */
    links?: object;
    /**
     * 
     * @type {object}
     * @memberof Components
     */
    callbacks?: object;
}

/**
 * Check if a given object implements the Components interface.
 */
export function instanceOfComponents(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ComponentsFromJSON(json: any): Components {
    return ComponentsFromJSONTyped(json, false);
}

export function ComponentsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Components {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'schemas': !exists(json, 'schemas') ? undefined : json['schemas'],
        'responses': !exists(json, 'responses') ? undefined : json['responses'],
        'parameters': !exists(json, 'parameters') ? undefined : json['parameters'],
        'examples': !exists(json, 'examples') ? undefined : json['examples'],
        'requestBodies': !exists(json, 'requestBodies') ? undefined : json['requestBodies'],
        'headers': !exists(json, 'headers') ? undefined : json['headers'],
        'securitySchemes': !exists(json, 'securitySchemes') ? undefined : json['securitySchemes'],
        'links': !exists(json, 'links') ? undefined : json['links'],
        'callbacks': !exists(json, 'callbacks') ? undefined : json['callbacks'],
    };
}

export function ComponentsToJSON(value?: Components | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'schemas': value.schemas,
        'responses': value.responses,
        'parameters': value.parameters,
        'examples': value.examples,
        'requestBodies': value.requestBodies,
        'headers': value.headers,
        'securitySchemes': value.securitySchemes,
        'links': value.links,
        'callbacks': value.callbacks,
    };
}

