/* tslint:disable */
/* eslint-disable */
/**
 * @betamanga/backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0-placeholder
 * Contact: kilian.panot@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExternalDocumentation
 */
export interface ExternalDocumentation {
    /**
     * 
     * @type {string}
     * @memberof ExternalDocumentation
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof ExternalDocumentation
     */
    url: string;
}

/**
 * Check if a given object implements the ExternalDocumentation interface.
 */
export function instanceOfExternalDocumentation(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "url" in value;

    return isInstance;
}

export function ExternalDocumentationFromJSON(json: any): ExternalDocumentation {
    return ExternalDocumentationFromJSONTyped(json, false);
}

export function ExternalDocumentationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExternalDocumentation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
        'url': json['url'],
    };
}

export function ExternalDocumentationToJSON(value?: ExternalDocumentation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'url': value.url,
    };
}

