/* tslint:disable */
/* eslint-disable */
/**
 * @betamanga/backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0-placeholder
 * Contact: kilian.panot@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostBasicAuthParameter
 */
export interface PostBasicAuthParameter {
    /**
     * Username to login
     * @type {string}
     * @memberof PostBasicAuthParameter
     */
    username: string;
    /**
     * Password of the user
     * @type {string}
     * @memberof PostBasicAuthParameter
     */
    password: string;
}

/**
 * Check if a given object implements the PostBasicAuthParameter interface.
 */
export function instanceOfPostBasicAuthParameter(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "username" in value;
    isInstance = isInstance && "password" in value;

    return isInstance;
}

export function PostBasicAuthParameterFromJSON(json: any): PostBasicAuthParameter {
    return PostBasicAuthParameterFromJSONTyped(json, false);
}

export function PostBasicAuthParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostBasicAuthParameter {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': json['username'],
        'password': json['password'],
    };
}

export function PostBasicAuthParameterToJSON(value?: PostBasicAuthParameter | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'password': value.password,
    };
}

