export enum Configurations {
  PORT = 'PORT',
  MONGODB_URL = 'MONGODB_URL',
  JWT_SECRET = 'JWT_SECRET',
  JWT_REFRESH_SECRET = 'JWT_REFRESH_SECRET',
  TOKEN_EXPIRES_IN = 'TOKEN_EXPIRES_IN',
  REFRESH_EXPIRES_IN = 'REFRESH_EXPIRES_IN',
}
